# Generated by Django 5.0.1 on 2024-01-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="", upload_to="cart/shop/static/shop/test.jpeg"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="sub_category",
            field=models.CharField(default="", max_length=50),
        ),
    ]
