# Generated by Django 5.0.1 on 2024-01-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_product_category_product_image_product_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(default="", upload_to="shop/images"),
        ),
    ]
