# Generated by Django 5.0.1 on 2024-03-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_orders"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderUpdate",
            fields=[
                ("update_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_id", models.IntegerField(default="")),
                ("update_desc", models.CharField(max_length=5000)),
                ("timestamp", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
