# Generated by Django 5.0.1 on 2024-04-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_orderupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="orders",
            name="items_json",
            field=models.CharField(max_length=50),
        ),
    ]
